# Generated by Django 5.1 on 2024-09-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0002_alter_link_click_count_alter_link_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='full_url',
            field=models.URLField(max_length=2048, verbose_name='Полный URL'),
        ),
    ]
