version: '3.8'

services:
  web:
    build: ./app
    container_name: link_shorter
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/datastore
    environment:
      - POSTGRES_USER=link_shorter
      - POSTGRES_PASSWORD=MCXIEBp100
      - POSTGRES_DB=link_shorter
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
volumes:
  postgres_data:
