# Generated by Django 5.1 on 2024-09-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='Количество кликов'),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='link',
            name='full_url',
            field=models.CharField(max_length=2048, verbose_name='Полный URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True, verbose_name='Короткий URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
